- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 9000 # 2.5 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 9000 # 2.5 hours
    - !type:DepartmentTimeRequirement
      department: Science
      time: 9000 # 2.5 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 9000 # 2.5 hrs
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 18000 # 5 hours
    - !type:AgeRequirement
      requiredAge: 21
  weight: 20
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  minBankBalance: 2800
  maxBankBalance: 3200
  wageDepartment: Command
  wage: 150

- type: startingGear
  id: HoPGear
  equipment:
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: HeadOfPersonnelChameleonOutfit
  job: HeadOfPersonnel
  hasMindShield: true
  equipment:
    head: ClothingHeadHatHopcap
    eyes: ClothingEyesHudCommand
    mask: ClothingMaskNeckGaiterRed
    neck: ClothingNeckCloakHop
    outerClothing: ClothingOuterWinterHoP

