ent-ClothingUniformRandom = { ent-ClothingUniformBase }
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual

ent-ClothingRandomSpawner = random colorful costume
    .desc = { ent-ClothingUniformRandom.desc }
    .suffix = { ent-ClothingUniformRandom.suffix }

ent-ClothingUniformRandomArmless = colorful hands-free costume
    .desc = { ent-ClothingUniformRandom.desc }
    .suffix = { ent-ClothingUniformRandom.suffix }

ent-ClothingUniformRandomStandart = colorful costume
    .desc = { ent-ClothingUniformRandom.desc }
    .suffix = { ent-ClothingUniformRandom.suffix }

ent-ClothingUniformRandomBra = colorful bra
    .desc = { ent-ClothingUniformRandom.desc }
    .suffix = { ent-ClothingUniformRandom.suffix }

ent-ClothingUniformRandomShorts = colorful pants
    .desc = { ent-ClothingUniformRandom.desc }
    .suffix = { ent-ClothingUniformRandom.suffix }

ent-ClothingUniformRandomShirt = colorful costume
    .desc = { ent-ClothingUniformRandom.desc }
    .suffix = { ent-ClothingUniformRandom.suffix }
