- type: entity
  id: BaseStationGoal
  abstract: true
  components:
    - type: StationGoal
      goals:
      - ShuttleRescue
      # - SolarPanels
      - Artifacts
      - Bar
      - Containment
      - Botany
      - Retranslator
      - ShuttlePatrol
      - Mechs

- type: entity
  id: BaseStationSiliconLawNTDefault
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: NTDefault

- type: entity
  id: BaseSyndicateStationShuttles
  abstract: true
  components:
    - type: GridSpawn
      groups:
        ruins: !type:GridSpawnGroup
          hide: true
          nameGrid: true
          minCount: 1
          maxCount: 2
          stationGrid: false
          paths:
          - /Maps/Ruins/abandoned_outpost.yml
          - /Maps/Ruins/atmos_interchange.yml
          - /Maps/Ruins/chunked_tcomms.yml
          - /Maps/Ruins/biodome_satellite.yml
          - /Maps/Ruins/derelict.yml
          - /Maps/Ruins/djstation.yml
          - /Maps/Ruins/empty_flagship.yml
          - /Maps/Ruins/hydro_outpost.yml
          - /Maps/Ruins/old_ai_sat.yml
          - /Maps/Ruins/ruined_prison_ship.yml
          - /Maps/Ruins/syndicate_dropship.yml
          - /Maps/Ruins/whiteship_ancient.yml
          - /Maps/Ruins/whiteship_bluespacejumper.yml
          - /Maps/Ruins/wrecklaimer.yml
          - /Maps/Ruins/displaced_telescience.yml
        wrecks: !type:DungeonSpawnGroup
          minimumDistance: 150
          maximumDistance: 700
          stationGrid: false
          minCount: 20
          maxCount: 55
          addComponents:
          - type: Gravity
            enabled: true
            inherent: true
          - type: IFF
            flags: HideLabel
            color: "#88b0d1"
          protos:
          - ChunkDebrisSmall
          - ChunkDebrisSmall
          - ChunkDebrisSmall
          - ChunkDebrisSmall
          - ChunkDebrisSmall
