- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  minBankBalance: 5000
  maxBankBalance: 6000
  wageDepartment: CentralCommand
  wage: 400
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
      - type: CentcommStaff
  whitelisted: true

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    back: ClothingBackpackSatchelHolding
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesCentcom
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterVestKevlarCent
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderCentCom
    pocket2: RubberStampCentcom
  storage:
    back:
    - Flash
    - DoorRemoteCentcom

- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
