using System;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;

namespace Content.Client.Info;

[GenerateTypedNameReferences]
public sealed partial class RulesLinksSection : BoxContainer
{
    public RulesLinksSection()
    {
        RobustXamlLoader.Load(this);

        var uriOpener = IoCManager.Resolve<IUriOpener>();
        var cfg = IoCManager.Resolve<IConfigurationManager>();

        DiscordButton.OnPressed += args => uriOpener.OpenUri(cfg.GetCVar(CCVars.InfoLinksDiscord));
        DiscordButton.Visible = cfg.GetCVar(CCVars.InfoLinksDiscord) != "";
        RolesButton.OnPressed += args => uriOpener.OpenUri(cfg.GetCVar(CCVars.InfoLinksRoles));
        RolesButton.Visible = cfg.GetCVar(CCVars.InfoLinksRoles) != "";
        LawsButton.OnPressed += args => uriOpener.OpenUri(cfg.GetCVar(CCVars.InfoLinksLaws));
        LawsButton.Visible = cfg.GetCVar(CCVars.InfoLinksLaws) != "";
    }
}
