using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.Economy.ATM.UI;

[GenerateTypedNameReferences]
public sealed partial class ATMEnterPinWindow : DefaultWindow
{
    public ATMEnterPinWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
