- type: job
  id: Mime
  name: job-name-mime
  description: job-description-mime
  playTimeTracker: JobMime
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers
      preventWriting: true
    - type: FrenchAccent
  minBankBalance: 350
  maxBankBalance: 550
  wageDepartment: Civilian
  wage: 40

- type: startingGear
  id: MimeGear
  equipment:
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesColorWhite
    id: MimePDA
    pocket1: CrayonMime
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampMime

- type: entity
  parent: BaseAction
  id: ActionMimeInvisibleWall
  name: Create Invisible Wall
  description: Create an invisible wall in front of you, if placeable there.
  components:
  - type: Action
    priority: -1
    useDelay: 30
    icon:
      sprite: Structures/Walls/solid.rsi
      state: full
  - type: InstantAction
    event: !type:InvisibleWallActionEvent

- type: chameleonOutfit
  id: MimeChameleonOutfit
  job: Mime
  equipment:
    head: ClothingHeadHatMimesoft
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingNeckScarfStripedZebra
    outerClothing: ClothingOuterWinterMime
